### ISSUE TITLE
Running the docker image

### ISSUE THREAD

**Issue by Meshredded** [getsandbox/worker-cli#42]
Hi,
I'm not able to run the docker image, when i do : 
`docker pull getsandbox/runtime && docker run -i -t getsandbox/runtime
`
I get : 
`Invalid base path`

Anyone can help please.

**Comment by stringy05** [comment]
You need to provide the path to your mocks - eg:

mock_dir % docker pull getsandbox/runtime && docker run --mount
type=bind,source=`pwd`,target=/base -i -t getsandbox/runtime
