### ISSUE TITLE
GET request doesn't support body

### ISSUE THREAD

**Issue by rafenden** [getsandbox/worker-cli#45]
GET requests doesn't support body which was working in the previous runtime.

Those kinds of request are required for ES queries.

**Comment by nhoughto** [comment]
Working on a fix for this atm

**Comment by nhoughto** [comment]
Fixed, building now..

**Comment by rafenden** [comment]
Thank you for a lighting fix! Are you planning to release it via GitHub releases?

**Comment by nhoughto** [comment]
Since expect the major usage will be from Docker, didn't think there as much value in github releases.
