### ISSUE TITLE
Do you still maintain this repository and update it to latest version used in Sandbox product?

### ISSUE THREAD

**Issue by cavoirom** [getsandbox/worker-cli#48]
Hello, thank you for impressive work and sorry for my rude question. I would like to know if the repository is still maintained, because I would like to build another project on top of this worker-cli. So that knowing the status of this project is important to me.

**Comment by nhoughto** [comment]
It is maintained, this repository isn't as tightly related to the actually running product as it used to be though. Changes can happen and be deployed there without necessarily being reflected here, which unfortunately leads to drift.

**Comment by Cfarrell111** [comment]
I have to open my case with the NYC Mayors Office for people with Disability's
