### ISSUE TITLE
Is this library vulnerable to log4j-library Log4Shell vulnerability?

### ISSUE THREAD

**Issue by ricbra** [getsandbox/worker-cli#50]
Hi guys, is this library also using log4j? I only found references to http://www.slf4j.org/ but not 100% sure that its not using log4j under the hood.

Thanks.

**Comment by nhoughto** [comment]
Nope. No log4j, we use log back or slf4j
Simple.

**Comment by ricbra** [comment]
Perfect, thanks for clearing that up so quickly 👍🏻
